# -*- coding: utf-8 -*-
"""analiseTexto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAjXXhVXIFhXu3ni0M_rj5aIMyrCqxR4

# Analise de Texto
----

**Importando Biliotecas**
"""

import requests
import string

"""**Importando Texto para tratamento**
- Utilizamos o site http://www.gutenberg.org para obtermos um texto
"""

resposta = requests.get('http://www.gutenberg.org/files/16429/16429-0.txt')

"""**Ajustando o encoding do Texto importado**"""

resposta.encoding = 'utf-8'

"""**Colocando todo o Texto em maiusculo**"""

texto = resposta.text.upper()

"""**Elimina texto inicial e final deixando apenas os contos**"""

texto = texto[texto.index('*A MÃE*') : texto.index('FIM.') -1]

"""**Removendo Pantuação do Texto**"""

texto = texto.translate(str.maketrans('', '', string.punctuation))
texto = texto.translate(str.maketrans('', '', '«»'))

"""**Retirando caracteres acentuados do texto**"""

!pip install unidecode
from unidecode import unidecode
texto = unidecode(texto)

"""**Separando texto em Palavras**"""

arrTexto = texto.split()

"""**Removendo StopWords**"""

!pip install nltk
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopWordPort = set(stopwords.words('portuguese'))
[palavra for palavra in arrTexto if palavra.lower() not in stopWordPort]
palavras_sem_stopwords = [palavra for palavra in arrTexto if palavra.lower() not in stopWordPort]
print(palavras_sem_stopwords)

"""**Gerando Frequencia das Palavras no Texto**"""

dic = {}

for x in palavras_sem_stopwords:
  if x in dic:
    dic[x] += 1
  else:
    dic[x] = 1
print(dic)

"""**Transformando o Dicionario emum DataFrame e Ordenando por Frequencia Decrescente**"""

import pandas as pd
dfpalavras = pd.DataFrame(dic.items(), columns=['Palavra', 'Frequencia'])
dfpalavras = dfpalavras.sort_values(by='Frequencia', ascending=False) 
print(dfpalavras)

"""# Nuvem de Palavras"""

!pip install wordcloud
!pip install matplotlib

from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(max_font_size=100,width = 1520, height = 535).generate(str(palavras_sem_stopwords))

plt.figure(figsize=(16,9))
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

